In [74]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/ADMIN/Downloads/Data/healthcare_dataset.csv")
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Tiffany Ramirez,81,Female,O-,Diabetes,2022-11-17,Patrick Parker,Wallace-Hamilton,Medicare,37490.983364,146,Elective,2022-12-01,Aspirin,Inconclusive
1,Ruben Burns,35,Male,O+,Asthma,2023-06-01,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064845,404,Emergency,2023-06-15,Lipitor,Normal
2,Chad Byrd,61,Male,B-,Obesity,2019-01-09,Paul Baker,Walton LLC,Medicare,36874.896997,292,Emergency,2019-02-08,Lipitor,Normal
3,Antonio Frederick,49,Male,B-,Asthma,2020-05-02,Brian Chandler,Garcia Ltd,Medicare,23303.322092,480,Urgent,2020-05-03,Penicillin,Abnormal
4,Mrs. Brandy Flowers,51,Male,O-,Arthritis,2021-07-09,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344184,477,Urgent,2021-08-02,Paracetamol,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,James Hood,83,Male,A+,Obesity,2022-07-29,Samuel Moody,"Wood, Martin and Simmons",UnitedHealthcare,39606.840083,110,Elective,2022-08-02,Ibuprofen,Abnormal
9996,Stephanie Evans,47,Female,AB+,Arthritis,2022-01-06,Christopher Yates,Nash-Krueger,Blue Cross,5995.717488,244,Emergency,2022-01-29,Ibuprofen,Normal
9997,Christopher Martinez,54,Male,B-,Arthritis,2022-07-01,Robert Nicholson,Larson and Sons,Blue Cross,49559.202905,312,Elective,2022-07-15,Ibuprofen,Normal
9998,Amanda Duke,84,Male,A+,Arthritis,2020-02-06,Jamie Lewis,Wilson-Lyons,UnitedHealthcare,25236.344761,420,Urgent,2020-02-26,Penicillin,Normal
9999,Eric King,20,Male,B-,Arthritis,2023-03-22,Tasha Avila,"Torres, Young and Stewart",Aetna,37223.965865,290,Emergency,2023-04-15,Penicillin,Abnormal

# Bài toán:dự đoán tiền viện phí (Billing Amount)

## Chọn ra những cột dữ liệu cần thiết để dự đoán

In [75]:
df = df[["Age","Gender","Blood Type","Medical Condition","Date of Admission","Insurance Provider","Admission Type","Discharge Date","Medication","Test Results","Billing Amount"]]
df

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Insurance Provider,Admission Type,Discharge Date,Medication,Test Results,Billing Amount
0,81,Female,O-,Diabetes,2022-11-17,Medicare,Elective,2022-12-01,Aspirin,Inconclusive,37490.983364
1,35,Male,O+,Asthma,2023-06-01,UnitedHealthcare,Emergency,2023-06-15,Lipitor,Normal,47304.064845
2,61,Male,B-,Obesity,2019-01-09,Medicare,Emergency,2019-02-08,Lipitor,Normal,36874.896997
3,49,Male,B-,Asthma,2020-05-02,Medicare,Urgent,2020-05-03,Penicillin,Abnormal,23303.322092
4,51,Male,O-,Arthritis,2021-07-09,UnitedHealthcare,Urgent,2021-08-02,Paracetamol,Normal,18086.344184
...,...,...,...,...,...,...,...,...,...,...,...
9995,83,Male,A+,Obesity,2022-07-29,UnitedHealthcare,Elective,2022-08-02,Ibuprofen,Abnormal,39606.840083
9996,47,Female,AB+,Arthritis,2022-01-06,Blue Cross,Emergency,2022-01-29,Ibuprofen,Normal,5995.717488
9997,54,Male,B-,Arthritis,2022-07-01,Blue Cross,Elective,2022-07-15,Ibuprofen,Normal,49559.202905
9998,84,Male,A+,Arthritis,2020-02-06,UnitedHealthcare,Urgent,2020-02-26,Penicillin,Normal,25236.344761
9999,20,Male,B-,Arthritis,2023-03-22,Aetna,Emergency,2023-04-15,Penicillin,Abnormal,37223.965865

## Kiểm tra các giá trị khác nhau của mỗi cột

In [76]:
for column in df.columns:
    if not pd.api.types.is_numeric_dtype(df[column]):
        unique_values = df[column].unique()
        print(f'{column}: {unique_values}')

Gender: ['Female' 'Male']
Blood Type: ['O-' 'O+' 'B-' 'AB+' 'A+' 'AB-' 'A-' 'B+']
Medical Condition: ['Diabetes' 'Asthma' 'Obesity' 'Arthritis' 'Hypertension' 'Cancer']
Date of Admission: ['2022-11-17' '2023-06-01' '2019-01-09' ... '2020-07-03' '2022-02-19'
 '2022-07-29']
Insurance Provider: ['Medicare' 'UnitedHealthcare' 'Aetna' 'Cigna' 'Blue Cross']
Admission Type: ['Elective' 'Emergency' 'Urgent']
Discharge Date: ['2022-12-01' '2023-06-15' '2019-02-08' ... '2023-01-02' '2019-05-23'
 '2023-11-27']
Medication: ['Aspirin' 'Lipitor' 'Penicillin' 'Paracetamol' 'Ibuprofen']
Test Results: ['Inconclusive' 'Normal' 'Abnormal']

## Tính số ngày nằm viện và thêm vào dữ liệu

In [77]:
from datetime import datetime
# Chuyển đổi các cột về định dạng datetime
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

# Tính số ngày nằm viện
df["Number of Days Hospitalized"] = (df["Discharge Date"] - df["Date of Admission"]).dt.days

# In ra DataFrame mới với cột "So ngay nam vien"
df

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9272\3746780016.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9272\3746780016.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9272\3746780016.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Number of Days Hospitalized"] = (df["Discharge Date"] - df["Date of Admission"]).dt.days

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Insurance Provider,Admission Type,Discharge Date,Medication,Test Results,Billing Amount,Number of Days Hospitalized
0,81,Female,O-,Diabetes,2022-11-17,Medicare,Elective,2022-12-01,Aspirin,Inconclusive,37490.983364,14
1,35,Male,O+,Asthma,2023-06-01,UnitedHealthcare,Emergency,2023-06-15,Lipitor,Normal,47304.064845,14
2,61,Male,B-,Obesity,2019-01-09,Medicare,Emergency,2019-02-08,Lipitor,Normal,36874.896997,30
3,49,Male,B-,Asthma,2020-05-02,Medicare,Urgent,2020-05-03,Penicillin,Abnormal,23303.322092,1
4,51,Male,O-,Arthritis,2021-07-09,UnitedHealthcare,Urgent,2021-08-02,Paracetamol,Normal,18086.344184,24
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,83,Male,A+,Obesity,2022-07-29,UnitedHealthcare,Elective,2022-08-02,Ibuprofen,Abnormal,39606.840083,4
9996,47,Female,AB+,Arthritis,2022-01-06,Blue Cross,Emergency,2022-01-29,Ibuprofen,Normal,5995.717488,23
9997,54,Male,B-,Arthritis,2022-07-01,Blue Cross,Elective,2022-07-15,Ibuprofen,Normal,49559.202905,14
9998,84,Male,A+,Arthritis,2020-02-06,UnitedHealthcare,Urgent,2020-02-26,Penicillin,Normal,25236.344761,20
9999,20,Male,B-,Arthritis,2023-03-22,Aetna,Emergency,2023-04-15,Penicillin,Abnormal,37223.965865,24

## Xóa ngày nhập viện và xuất viện

In [78]:
df = df.drop(columns =["Date of Admission","Discharge Date"])
df

,Age,Gender,Blood Type,Medical Condition,Insurance Provider,Admission Type,Medication,Test Results,Billing Amount,Number of Days Hospitalized
0,81,Female,O-,Diabetes,Medicare,Elective,Aspirin,Inconclusive,37490.983364,14
1,35,Male,O+,Asthma,UnitedHealthcare,Emergency,Lipitor,Normal,47304.064845,14
2,61,Male,B-,Obesity,Medicare,Emergency,Lipitor,Normal,36874.896997,30
3,49,Male,B-,Asthma,Medicare,Urgent,Penicillin,Abnormal,23303.322092,1
4,51,Male,O-,Arthritis,UnitedHealthcare,Urgent,Paracetamol,Normal,18086.344184,24
...,...,...,...,...,...,...,...,...,...,...
9995,83,Male,A+,Obesity,UnitedHealthcare,Elective,Ibuprofen,Abnormal,39606.840083,4
9996,47,Female,AB+,Arthritis,Blue Cross,Emergency,Ibuprofen,Normal,5995.717488,23
9997,54,Male,B-,Arthritis,Blue Cross,Elective,Ibuprofen,Normal,49559.202905,14
9998,84,Male,A+,Arthritis,UnitedHealthcare,Urgent,Penicillin,Normal,25236.344761,20
9999,20,Male,B-,Arthritis,Aetna,Emergency,Penicillin,Abnormal,37223.965865,24

## Mã hóa dữ liệu

In [79]:
# Chọn các cột cần mã hóa
columns_to_encode = ['Gender',"Blood Type", 'Medical Condition',"Insurance Provider", 'Admission Type', 'Medication',"Test Results"]

# Mã hóa các cột bằng dummy variables và chuyển đổi thành giá trị 0 và 1
dummies = pd.get_dummies(df[columns_to_encode], prefix=columns_to_encode, drop_first=True).astype(int)

# Thêm các cột đã mã hóa vào DataFrame gốc
df = pd.concat([df, dummies], axis=1)

# Loại bỏ các cột gốc đã được mã hóa
df = df.drop(columns=columns_to_encode)

# Hiển thị DataFrame sau khi thực hiện
df

,Age,Billing Amount,Number of Days Hospitalized,Gender_Male,Blood Type_A-,Blood Type_AB+,Blood Type_AB-,Blood Type_B+,Blood Type_B-,Blood Type_O+,...,Insurance Provider_Medicare,Insurance Provider_UnitedHealthcare,Admission Type_Emergency,Admission Type_Urgent,Medication_Ibuprofen,Medication_Lipitor,Medication_Paracetamol,Medication_Penicillin,Test Results_Inconclusive,Test Results_Normal
0,81,37490.983364,14,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
1,35,47304.064845,14,1,0,0,0,0,0,1,...,0,1,1,0,0,1,0,0,0,1
2,61,36874.896997,30,1,0,0,0,0,1,0,...,1,0,1,0,0,1,0,0,0,1
3,49,23303.322092,1,1,0,0,0,0,1,0,...,1,0,0,1,0,0,0,1,0,0
4,51,18086.344184,24,1,0,0,0,0,0,0,...,0,1,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,83,39606.840083,4,1,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
9996,47,5995.717488,23,0,0,1,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
9997,54,49559.202905,14,1,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
9998,84,25236.344761,20,1,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,1
9999,20,37223.965865,24,1,0,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0

## Chuẩn hóa dữ liệu

In [80]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Chọn các cột cần chuẩn hóa
columns = ["Age","Number of Days Hospitalized"]

# Chuẩn hóa dữ liệu và gán lại cho DataFrame
df[columns] = scaler.fit_transform(df[columns])

# In DataFrame sau khi chuẩn hóa
df

,Age,Billing Amount,Number of Days Hospitalized,Gender_Male,Blood Type_A-,Blood Type_AB+,Blood Type_AB-,Blood Type_B+,Blood Type_B-,Blood Type_O+,...,Insurance Provider_Medicare,Insurance Provider_UnitedHealthcare,Admission Type_Emergency,Admission Type_Urgent,Medication_Ibuprofen,Medication_Lipitor,Medication_Paracetamol,Medication_Penicillin,Test Results_Inconclusive,Test Results_Normal
0,1.508465,37490.983364,-0.181360,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
1,-0.839912,47304.064845,-0.181360,1,0,0,0,0,0,1,...,0,1,1,0,0,1,0,0,0,1
2,0.487431,36874.896997,1.676598,1,0,0,0,0,1,0,...,1,0,1,0,0,1,0,0,0,1
3,-0.125189,23303.322092,-1.690950,1,0,0,0,0,1,0,...,1,0,0,1,0,0,0,1,0,0
4,-0.023086,18086.344184,0.979864,1,0,0,0,0,0,0,...,0,1,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.610568,39606.840083,-1.342583,1,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
9996,-0.227292,5995.717488,0.863741,0,0,1,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
9997,0.130069,49559.202905,-0.181360,1,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
9998,1.661620,25236.344761,0.515374,1,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,1
9999,-1.605688,37223.965865,0.979864,1,0,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0

## Chia mô hình

In [81]:
feature = df.iloc[:, [0] + list(range(2, len(df.columns)))]
target = df.iloc[:,1]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feature, target, test_size=0.2, random_state=42)

## Tạo mô hình - huấn luyện - dự đoán

In [82]:
from sklearn.linear_model import LinearRegression
# Tạo mô hình hồi quy
model = LinearRegression()

# Huấn luyện mô hình trên tập huấn luyện
model.fit(X_train, y_train)

# Dự đoán giá trên tập kiểm tra
y_predict = model.predict(X_test)
y_predict

array([26737.33056968, 23251.19861453, 27041.86602153, ...,
       24628.40554072, 25409.16881247, 27580.37655223])

## Kiểm tra độ chính xác

In [83]:
from sklearn.metrics import mean_squared_error, r2_score

# Tính MSE
mse = mean_squared_error(y_test, y_predict)
print(f"Mean Squared Error: {mse}")

# Tính R2 score
r2 = r2_score(y_test, y_predict)
print(f"R-squared: {r2}")

Mean Squared Error: 199666388.74760485
R-squared: 0.0010831361179078902